version: '3'
services:
  webpack:
    build:
      context: ./webpack
    ports:
      - "8888:8888"
    container_name: reactjs_webpack_container
    command: ["node", "server.js"]
    env_file: secret.env
    volumes:
      - ./webpack:/app:z
      - /app/node_modules
    dns: 192.168.1.1
    links:
      - redis
  redis:
    image: redis:4.0.9
    volumes: 
      - ./redis:/data
    command: redis-server --appendonly yes